
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gaurav
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public ResultSet getData(String query)
    {  
        String URL="jdbc:mysql://localhost/Assignment";
        String USERNAME="root";
        String PASSWORD="gaurav";
    
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection(URL,USERNAME,PASSWORD);
            st=con.createStatement();
            rs=st.executeQuery(query);
            return rs;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e+"Error While building connection with database..! ");
        }
        return rs;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JPanel();
        logo_lb = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        user_lb = new javax.swing.JLabel();
        user_tf = new javax.swing.JTextField();
        pass_pf = new javax.swing.JPasswordField();
        pass_lb = new javax.swing.JLabel();
        userpic_lb = new javax.swing.JLabel();
        showpasspic_lb = new javax.swing.JLabel();
        login_lb = new javax.swing.JLabel();
        login_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(25, 118, 211));

        logo_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grlogo.png"))); // NOI18N

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(logo_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addComponent(logo_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 170, Short.MAX_VALUE))
        );

        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 370));

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        right.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, -1));
        right.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 330, 10));

        user_lb.setBackground(new java.awt.Color(255, 255, 255));
        user_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 28)); // NOI18N
        user_lb.setForeground(new java.awt.Color(25, 118, 211));
        user_lb.setText("Username");
        right.add(user_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        user_tf.setFont(new java.awt.Font("Aharoni", 0, 20)); // NOI18N
        user_tf.setForeground(new java.awt.Color(60, 60, 60));
        user_tf.setBorder(null);
        user_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_tfFocusLost(evt);
            }
        });
        user_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_tfMouseExited(evt);
            }
        });
        user_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_tfActionPerformed(evt);
            }
        });
        right.add(user_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, 40));

        pass_pf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pass_pf.setForeground(new java.awt.Color(60, 60, 60));
        pass_pf.setBorder(null);
        pass_pf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_pfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_pfFocusLost(evt);
            }
        });
        pass_pf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pass_pfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pass_pfMouseExited(evt);
            }
        });
        right.add(pass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 40));

        pass_lb.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 28)); // NOI18N
        pass_lb.setForeground(new java.awt.Color(25, 118, 211));
        pass_lb.setText("Password");
        right.add(pass_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        userpic_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_male_30px.png"))); // NOI18N
        right.add(userpic_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 30));

        showpasspic_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_key_2_30px.png"))); // NOI18N
        right.add(showpasspic_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 30, 30));

        login_lb.setBackground(new java.awt.Color(255, 255, 255));
        login_lb.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        login_lb.setForeground(new java.awt.Color(25, 118, 211));
        login_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_lb.setText("<html><U>Login</html></U>");
        right.add(login_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 40));

        login_bt.setBackground(new java.awt.Color(255, 255, 255));
        login_bt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        login_bt.setForeground(new java.awt.Color(25, 118, 211));
        login_bt.setText("Login");
        login_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btActionPerformed(evt);
            }
        });
        right.add(login_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 370, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btActionPerformed
String user="",pass="";
user=user_tf.getText();
pass=pass_pf.getText();
if  (user.equals("") || pass.equals(""))  {
    JOptionPane.showMessageDialog(this, "Username and Password should not be Empty.!!!","Fill all Fields",JOptionPane.INFORMATION_MESSAGE);
    return;
}
    String query="Select PASSWORD from LOGINTEST where USERNAME='"+user+"'";
    dbConnectivity db=new dbConnectivity();
    db.getRecord(query);
    
    try {
        db.r.next();
        if(db.r.getString("PASSWORD").equals(pass)){
            System.out.println(db.r.getString("PASSWORD"));
            JOptionPane.showMessageDialog(null, "Welcome "+user+"..!","Login Sucessfully..!",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Username and Password does not match..! ","Invalid Password..!!",JOptionPane.ERROR_MESSAGE);
        }              
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "User not registered..!","Restered First",JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_login_btActionPerformed

    private void user_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_tfFocusGained

    }//GEN-LAST:event_user_tfFocusGained

    private void user_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_tfFocusLost

    }//GEN-LAST:event_user_tfFocusLost

    private void user_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tfMouseEntered

    }//GEN-LAST:event_user_tfMouseEntered

    private void user_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tfMouseExited

    }//GEN-LAST:event_user_tfMouseExited

    private void user_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_tfActionPerformed

    private void pass_pfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_pfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_pfFocusGained

    private void pass_pfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_pfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_pfFocusLost

    private void pass_pfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_pfMouseEntered

    }//GEN-LAST:event_pass_pfMouseEntered

    private void pass_pfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_pfMouseExited

    }//GEN-LAST:event_pass_pfMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel left;
    private javax.swing.JButton login_bt;
    private javax.swing.JLabel login_lb;
    private javax.swing.JLabel logo_lb;
    private javax.swing.JLabel pass_lb;
    private javax.swing.JPasswordField pass_pf;
    private javax.swing.JPanel right;
    private javax.swing.JLabel showpasspic_lb;
    private javax.swing.JLabel user_lb;
    private javax.swing.JTextField user_tf;
    private javax.swing.JLabel userpic_lb;
    // End of variables declaration//GEN-END:variables
}
